'use strict';

/**
 * Audit-Event-Namen für das ThreatHunting-Modul.
 *
 * Single Source of Truth — alle Services und Tests importieren von hier.
 * Niemals String-Literals in Services/Routes verwenden.
 */
const HUNT_AUDIT_EVENTS = Object.freeze({
  // Session
  SESSION_CREATED:    'HUNT_SESSION_CREATED',
  SESSION_ACTIVATED:  'HUNT_SESSION_ACTIVATED',
  SESSION_COMPLETED:  'HUNT_SESSION_COMPLETED',
  SESSION_FAILED:     'HUNT_SESSION_FAILED',
  SESSION_CANCELLED:  'HUNT_SESSION_CANCELLED',

  // Command
  COMMAND_ADDED:      'HUNT_COMMAND_ADDED',
  COMMAND_STARTED:    'HUNT_COMMAND_STARTED',
  COMMAND_COMPLETED:  'HUNT_COMMAND_COMPLETED',
  COMMAND_FAILED:     'HUNT_COMMAND_FAILED',
  COMMAND_BLOCKED:    'HUNT_COMMAND_BLOCKED',
  COMMAND_REQUEUED:   'HUNT_COMMAND_REQUEUED',

  // Artifact
  ARTIFACT_COLLECTED: 'HUNT_ARTIFACT_COLLECTED',

  // Finding
  FINDING_CREATED:      'HUNT_FINDING_CREATED',
  FINDING_VERDICT_SET:  'HUNT_FINDING_VERDICT_SET',

  // Ticket-Links (P13.4)
  FINDING_LINKED:     'HUNT_FINDING_LINKED_TO_TICKET',
  ARTIFACT_LINKED:    'HUNT_ARTIFACT_LINKED_TO_TICKET',
  SUMMARY_LINKED:     'HUNT_SUMMARY_LINKED_TO_TICKET',

  // Note
  NOTE_ADDED:         'HUNT_NOTE_ADDED',
});

module.exports = { HUNT_AUDIT_EVENTS };
